### ISSUE TITLE
Check the token before the API call

### ISSUE THREAD

**Issue by developer-hola** [LoginRadius/html5-sdk#2]
Hi,

At this moment each call we need to do, for example readAllProfilesByToken, needs us to check if the user token is defined. I think it can be better for your library to check before doing the API call if this token is defined.

This is our code:
if(LoginRadiusSDK.getToken()){
   var data = LoginRadiusSDK.readAllprofilesByToken();
   if(data){
       //check data
   }
}

And we think that this solution can be better:
var data = LoginRadiusSDK.readAllprofilesByToken();
   if(data){
       //check data
   }

Thanks.

**Comment by Karl-LoginRadius** [comment]
Hi, 

This improvement will be included in the next iteration of the HTML/JS SDK. 

Thanks,

**Comment by Karl-LoginRadius** [comment]
This has been released
