### ISSUE TITLE
Change to lower case the first letter of error Msg

### ISSUE THREAD

**Issue by developer-hola** [LoginRadius/html5-sdk#3]
Hi, in the response of your API the key errorCode come  with camel case with the first letter in lower case, but in the JS SDK in the var errorMsgs  the kay come with the first letter on upper case, can you change to lower case this letter? we have all the implementation with the first letter in lower case.

**Comment by Karl-LoginRadius** [comment]
Hi, 

In the V2 version of the LoginRadius API all error messages are returned in the standard format with the ErrorCode key. You can see this format on our documentation here: https://docs.loginradius.com/api/v2/getting-started/data-points-and-response-codes/error-codes

In the v1 version of the SDK this returned in the lowercase errorCode format. 

Thanks,

**Comment by developer-hola** [comment]
Thnaks
